---
apiVersion: v1
kind: Pod
metadata:
    name: docker-builder
spec:
    volumes:
        - name: secret-volume
          secret:
              secretName: docker-hub-auth 
    containers:
        - name: docker-builder
          image: gcr.io/kaniko-project/executor:latest
          args: ["--dockerfile=Dockerfile", "--context=git://github.com/shikloshi/kaniko-poc.git", "--destination=shikloshi/kaniko-poc:1.0"]
          volumeMounts:
              - name: secret-volume
                readOnly: true
                mountPath: "/kaniko/.docker"
